version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-openrouter-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  bot-network:
    driver: bridge